version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: smart_realtor
      POSTGRES_PASSWORD: "zTMgq-EggYbere_uXBm80pYyQgOpdMAe"
    volumes:
      - smart_realtor_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "60glj1V4fcCyD20UwyjubBlG50Ec8DPz"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  smart_realtor_data:
